committing to portfolio-files branch
NikhithaReddy-26/Portfolio pull request #1
Opened 2023-03-02 12:00 UTC by NikhithaReddy-26

2023-03-06 06:51 UTC, msaisrinivas requested changes

2023-03-06 06:51 UTC, msaisrinivas commented on .vscode/settings.json
> +{
remove the unwanted files

2023-03-06 07:17 UTC, NikhithaReddy-26 commented on .vscode/settings.json
> +{
Done

2023-03-08 07:37 UTC, msaisrinivas approved these changes

2023-04-27 11:04 UTC, merged